RolesScheduler/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("agenda.urls", namespace="agenda")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agenda/urls.py
from django.urls import path

from . import views

app_name = "agenda"

urlpatterns = [
    path("", views.index, name="index"),
    path("spreadsheet", views.spreadsheet, name="spreadsheet"),
    path("profile/<id>", views.profile, name="profile"),
    path("meeting/<id>", views.meeting, name="meeting"),
    path("edit_meeting/<id>", views.edit_meeting, name="edit_meeting"),
    path("create_meeting", views.create_meeting, name="create_meeting"),
    path("bulk_create_meeting", views.bulk_create_meeting, name="bulk_create_meeting"),
    path("delete_meeting/<id>", views.delete_meeting, name="delete_meeting"),
    path("meeting_list", views.meeting_list, name="meeting_list"),
    path("report_bug", views.report_bug, name="report_bug"),
    path("bug_list", views.bug_list, name="bug_list"),
    path("update_role_description/<id>", views.update_role_description, name="update_role_description"),
    path("confirmation_emails/<id>", views.confirmation_emails, name="confirmation_emails"),
    path("update_guest_list/<id>", views.update_guest_list, name="update_guest_list"),

    # Meeting Confirmation from email routes
    path("confirm_attendance/<id>/<username>/<status>", views.confirm_attendance, name="confirm_attendance"),

    # Authentication routes
    path("register/", views.register, name="register"),
    path("create_user/", views.create_user, name="create_user"),

    # API Routes
    path("attendence", views.attendence, name="attendence"),
    path("sign_up", views.sign_up, name="sign_up"),
    path("fetch_call_recommend_one_role", views.fetch_call_recommend_one_role, name="fetch_call_recommend_one_role"),
    path("change_event_number", views.change_event_number, name="change_event_number"),
    path("add_new_event", views.add_new_event, name="add_new_event"),
]

agenda/views.py
import time
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Q
from re import findall
from django.http import JsonResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from datetime import datetime, timedelta, time, date
from django.views.decorators.csrf import csrf_exempt, csrf_protect
import random
import string
from django.conf import settings 
from django.core.mail import send_mail, EmailMessage

from .models import User, Meeting, Rolelist, Attendee, BugForm, Buglist, Eventlist
from .functions import update_meeting, meeting_roles_list, update_one_role_in_database, create_default_eventlist, role_recommendation_list, past_role_holders, convert_role_to_shorthand


# View the first upcoming meeting's individual page
def index(request):
    
    # Get the start and end dates for the meeting query
    startdate = date.today()
    enddate = startdate + timedelta(days=365)

    # Get the next meeting
    next_meeting = Meeting.objects.filter(starttime__range=[startdate, enddate]).order_by('starttime').first()

    if next_meeting == None:
        return HttpResponseRedirect(reverse("agenda:meeting_list"))

    # Redirect to views.meeting to load the individual meeting page for the next meeting
    return HttpResponseRedirect(reverse("agenda:meeting", args=(next_meeting.id,)))


# View individual meeting page
def meeting(request, id):

    # Reset the alert notifications
    alert_success = None
    alert_danger = None

    # Get the next meeting information
    meeting = Meeting.objects.filter(id=id).order_by('-starttime')
    
    roles = Rolelist.objects.filter(meeting=meeting[0])
    rolelist = meeting_roles_list(meeting[0])

    # Get the role recommednations for the selected meeting
    role_recommendations = role_recommendation_list(meeting[0])
        
    # Add role recommendations to the rolelist
    # Iterate through all the roles in the rolelist
    for role in rolelist:

        # If no one is assigned to the role, get a list of recommendations. Else skip to next role
        if rolelist[role] == None:

            # Add recommednations to the rolelist
            rolelist[role] = ['No Member Assigned', role_recommendations[role]]

    attendees = Attendee.objects.filter(meeting=meeting[0])
    confirmed_attendees = []
    unknown_attendees = []
    absentees = []
    for attendee in attendees:
        if attendee.status == "U":
            unknown_attendees.append(attendee.user)

            # Check if logged in user has marked their attendance
            if str(attendee.user.username) == str(request.user.username):
                alert_danger = f"You haven't confirmed your attendence for this meeting yet."
        elif attendee.status == "F":
            absentees.append(attendee.user)
        elif attendee.status == "T":
            confirmed_attendees.append(attendee.user)

    # Get the eventlist for the meeting
    eventlist = Eventlist.objects.filter(meeting=meeting[0]).order_by('event_number').values()

    # Update eventlist with role holders
    for event in eventlist:
        if event['role'] != "" and event['role'] != "None" and event['role'] != None:
            event['user'] = rolelist[event['role']]

    # Add start times to each event based on the durations
    f = '%I:%M'
    t = meeting[0].starttime
    printer = t.strftime("%X")
    for event in eventlist:
        # Print event start time to eventlist
        event['start_time'] = t.strftime(f)

        # Update event start time for the next event
        min_to_add = event['duration']
        t = t + timedelta(minutes = min_to_add)
    
    # Remind users to login or register in roder to sign up for roles and speeches
    if request.user.is_authenticated == False:
        alert_danger = f"Login to sign up for a role or speech this meeting."

    # Get the list of all bugs reported
    bugs = Buglist.objects.filter()

    print(rolelist)
    print(roles[0].zoom)

    # Render the individual meeting page
    return render(request, "agenda/meeting.html", {
        'id': id,
        "meeting": meeting[0],
        "roles": roles[0],
        'rolelist': rolelist,
        'eventlist': eventlist,
        'confirmed_attendees': confirmed_attendees,
        'unknown_attendees': unknown_attendees,
        'absentees': absentees,
        'username': str(request.user.username),
        'alert_success': alert_success,
        'alert_danger': alert_danger,
        'bugs': bugs,
    })


def meeting_list(request):

    # Get the start and end dates for the next year
    startdate = date.today() - timedelta(days=30)
    enddate = startdate + timedelta(days=396)

    # Get the list of meetings for the next year
    meeting_list_query = Meeting.objects.filter(starttime__range=[startdate, enddate]).order_by('starttime')

    # Setup the meeting list with dates and role holders
    list_of_meetings = []
    for meeting in meeting_list_query:
        print(meeting.theme)

        # Get the toastmaster for the meeting
        role_query = Rolelist.objects.filter(meeting=meeting).values('toastmaster')
        if role_query[0]['toastmaster'] == None:
            toastmaster = None
        else:
            toastmaster = User.objects.get(id=role_query[0]['toastmaster'])

        # Get the general evaluator for the meeting
        role_query =  Rolelist.objects.filter(meeting=meeting).values('geneval')
        if role_query[0]['geneval'] == None:
            geneval = None
        else:
            geneval = User.objects.get(id=role_query[0]['geneval'])

        # Get the table topics master for the meeting
        role_query = Rolelist.objects.filter(meeting=meeting).values('ttmaster')
        if role_query[0]['ttmaster'] == None:
            ttmaster = None
        else:
            ttmaster = User.objects.get(id=role_query[0]['ttmaster'])

        # Get the number of speeches for the meeting
        speech_count = 0
        speech_query = Rolelist.objects.filter(meeting=meeting).values('speaker1', 'speaker2', 'speaker3')
        for speech in speech_query[0]:
            if speech_query[0][speech] != None:
                speech_count += 1

        # Add id's, dates, and role holders to the list
        meeting_entry_for_the_list = {'id': meeting.id, 'date': meeting.starttime.strftime("%d/%b/%Y"), 'theme': meeting.theme,'speech_count': speech_count, 'toastmaster': toastmaster, 'geneval': geneval, 'ttmaster': ttmaster}
        
        # Add dictionary for the individual meeting to the list of all meetings to be passed to the template to display
        list_of_meetings.append(meeting_entry_for_the_list)

    # Render the list of meetings
    return render(request, "agenda/meeting_list.html", {
        'meeting_list': list_of_meetings
    })


@login_required
def profile(request, id):
    
    # Get User information
    user = User.objects.get(id=id)
    print(user)
    
    return render(request, "agenda/profile.html", {
    })


@login_required
def edit_meeting(request, id):

    # If user is submitting the edit meeting form
    if request.method == "POST":
        # Get data from form submission
        form = request.POST
        print(form)

        # Get the existing meeting information
        meeting = Meeting.objects.get(id=id)

        # Update meeting information
        print(meeting, form)
        update_meeting(meeting, form)

        return HttpResponseRedirect(reverse("agenda:meeting", args=(id,)))

    
    # Get meeting details
    meeting = Meeting.objects.filter(id=id)

    # Check if this is a new meeting
    if not meeting:
        
        # Create a new meeting
        new_meeting = Meeting(id=id, starttime=datetime.now())
        new_meeting.save()

        # Create a new rolelist
        new_rolelist = Rolelist(meeting=new_meeting)
        new_rolelist.save()

        # Create a new Eventlist
        create_default_eventlist(new_meeting)

        # Mark all attendees as unknown
        users = User.objects.filter()
        for user in users:
            new_attendence = Attendee(user=user, meeting=new_meeting, status="U")
            new_attendence.save()

        #Reset meeting variable to new meeting
        meeting = Meeting.objects.filter(id=id)
        
    # Get all attending User details
    users = []
    attendees = Attendee.objects.filter(meeting=meeting[0])
    for attendee in attendees:
        if attendee.status != "F":
            users.append(attendee.user)

    meeting = meeting[0]
    roles = meeting_roles_list(meeting)

    # Get the meeting time and date
    start_time = meeting.starttime.time().strftime("%H:%M")
    start_date = meeting.starttime.date().strftime("%Y-%m-%d")

    # Get the eventlist for the meeting
    eventlist = Eventlist.objects.filter(meeting=meeting).order_by('event_number').values()

    return render(request, "agenda/edit_meeting.html", {
        'new_meeting': False,
        'id': id,
        'meeting': meeting,
        'start_date': start_date,
        'start_time': start_time,
        'roles': roles,
        'users': users,
        'eventlist': eventlist,
    })


@login_required
def create_meeting(request):

    # Get the list of meetings ordered highest id first
    meeting = Meeting.objects.filter().order_by('-id').first()

    # If no meetings exist yet set id to 1
    if meeting == None:
        id = 1
    
    # Else add 1 to the highest id
    elif meeting != None:
        id = meeting.id + 1

    return HttpResponseRedirect(reverse("agenda:edit_meeting", args=(id,)))


@login_required
def bulk_create_meeting(request):

    # Check if the user is submitting the bulk meeting creation form
    if request.method == 'POST':
        # Get data from form submission
        form = request.POST

agenda/templates/agenda/bug_list.html
{% extends 'agenda/layout.html' %}
{% load static %}

{% block title %}
    Bug List
{% endblock %}

{% block body %}
<br>

<div class="container col-title">
    <h2>List of Bugs Users have Reported</h2>
</div>

<br>

<table class="container table table-striped table-hover">
    <thead>
        <tr>
            <th>
                Type
            </th>
            <th>
                Location
            </th>
            <th>
                Description
            </th>
            <th>
                User
            </th>
            <th>
                Date
            </th>
        </tr>
    </thead>
    <tbody>
        {% for bug in bug_list %}
            <tr>
                <td>
                    {{ bug.bug_type }}
                </td>
                <td>
                    {{ bug.bug_location }}
                </td>
                <td>
                    {{ bug.bug_description }}
                </td>
                <td>
                    {{ bug.user }}
                </td>
                <td>
                    {{ bug.date_reported }}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

agenda/templates/agenda/bug_report.html
{% extends 'agenda/layout.html' %}
{% load static %}

{% block title %}
    Report a Bug
{% endblock %}

{% block body %}
<br>

    <div class="container container-sm col-title col-6">
        <h2>Report a Bug</h2>
    </div>

    <br>

    <div class="container container-sm col-title col-6">
        <p>Thank you for reporting a bug!</p>
        <p>This webapp is still in alpha and there are a lot of kinks left to work out. Every bug you report gets us one step closer to launching a full version of the webapp.</p>

        <form action="{% url 'agenda:report_bug' %}" method="post">
            {% csrf_token %}

            {{ bug_report_form.non_field_errors }}

            <div class="fieldWrapper">
                {{ bug_report_form.bug_type.errors }}
                {{ bug_report_form.bug_type.label_tag }}
                {{ bug_report_form.bug_type }}
            </div>
            <div class="fieldWrapper">
                {{ bug_report_form.bug_location.errors }}
                {{ bug_report_form.bug_location.label_tag }}
                {{ bug_report_form.bug_location }}
            </div>
            <div class="fieldWrapper">
                {{ bug_report_form.bug_description.errors }}
                {{ bug_report_form.bug_description.label_tag }}
                {{ bug_report_form.bug_description }}
            </div>
            <div class="fieldWrapper">
                {{ bug_report_form.contact_info.errors }}
                {{ bug_report_form.contact_info.label_tag }}
                {{ bug_report_form.contact_info }}
            </div>

            <br>

            <button type="submit" class="btn btn-primary">Submit Bug Report</button>
        </form>
    </div>

    <br>

    <!--Section to explain the differebnt types fo bugs-->
    <div class="container container-sm col-title col-6">

        <h4>Bug Type Explanations</h4>
        <p>Don't worry too much about the type you select. The developper will try to fix all bugs reported, selecting a type just helps them decide the order.</p>
        
        <br>

            <figure>
            <blockquote cite="https://devqa.io/what-to-include-in-bug-report/">
                <h5>Critical Bugs</h5>
                <p>This means the defect is a show stopper with high potential damages and has no workaround to avoid the defect. An example could be the application does not launch at all and causes the operating system to shut down. This requires immediate attention and action and fix.</p>

                <h5>Serious Bugs</h5>
                <p>This means that some major functionalities of the applications are either missing or do not work and there is no workaround. Example, an image viewing application cannot read some common image formats.</p>

                <h5>Normal Bugs</h5>
                <p>This means that some major functionality do not work, but, a workaround exists to be used as a temporary solution.</p>

                <h5>Cosmetic/Enhancements</h5>
                <p>This means that the failure causes inconvenience and annoyance. Example can be that there is a pop-up message every 15 minutes, or you always have to click twice on a button to perform the action.</p>

                <h5>Suggestions</h5>
                <p>This is not normally a defect and a suggestion to improve a functionality. This can be GUI or viewing preferences.</p>
            </blockquote>
            <figcaption>—Amir Ghahrai, DevQA.io, <cite>What to Include in a Bug Report?</cite></figcaption>
        </figure>

    </div>

{% endblock %}

agenda/templates/agenda/bulk_create_meetings.html
{% extends 'agenda/layout.html' %}
{% load static %}

{% block title %}
    Bulk Create Meetings
{% endblock %}

{% block body %}
    <br>

    <!--Page Title-->
    <div class="container container-sm col-title col-8">
        <h2>Bulk Create Meetings</h2>
    </div>

    <br>

    <!--Create Meetings Form-->
    <div class="container container-sm col-title col-8">
        <form method="POST">
            {% csrf_token %}

            <!--Start Date-->
            <div class="form-group">
                <label for="start_date">Start Date:</label>
                <input type="date" id="start_date" name="start_date" class="form-control" value="{{ date_today }}" required>
            </div>

            <!--End Date-->
            <div class="form-group">
                <label for="end_date">End Date:</label>
                <input type="date" id="end_date" name="end_date" class="form-control" value="" required>
            </div>

            <!--Which Day of the Week-->
            <div class="form-group">
                <label for="ens_date">Day of the Week:</label>
                <select class="form-select form-control" id="day_of_the_week" name="day_of_the_week" required>
                    <option value="0">Monday</option>
                    <option value="1" selected>Tuesday</option>
                    <option value="2">Wednesday</option>
                    <option value="3">Thursday</option>
                    <option value="4">Friday</option>
                    <option value="5">Saturday</option>
                    <option value="6">Sunday</option>
                </select>
            </div>

            <!--Time of day-->
            <div class="form-group">
                <label for="start_time">Start Time:</label>
                <input type="time" id="start_time" name="start_time" class="form-control" value="18:10" required>
            </div>

            <!--Submit button-->
            <button type="submit" class="btn btn-primary mb-3">Create Meetings</button>
        </form>
    </div>

{% endblock %}

agenda/templates/agenda/confirmation_emails.html
{% extends 'agenda/layout.html' %}
{% load static %}

{% block title %}
    Email Confirmations
{% endblock %}

{% block body %}

<br>

    <div class="container container-sm col-title col-8">
        <h2>Send Email Confirmations for Meeting on: {{ meeting.starttime|date:"M d, Y" }}</h2>
    </div>

    <br>

    <!--Attendance Confirmation Emails Dashboard-->
    <div class="container container-sm col-title col-8">
        <h4>1) Attendance Confirmations</h4>
        <p>Send a confirmation email to all members with Unknown Attendence at the Meeting.</p>
        <p>List of members with unknown attendance: 
            {% for member in unknown_attendees %}
                <b>{{ member.username }}</b>, 
            {% endfor %}
        </p>

        <!--The actual email form-->
        <form action="/confirmation_emails/{{ meeting.id }}" method="POST">
            {% csrf_token %}
            <div class="form-group"> <!--Recipients list-->
                <label for="recipients">Recipients:</label>
                <input type="text" id="recipients" name="recipients" class="form-control" value="{% for member in unknown_attendees %}{{ member.email }} {% endfor %}" required>
            </div>
            <div class="form-group"> <!--Email that will send out the email-->
                <label for="from">From:</label>
                <input type="text" id="from" name="from" class="form-control" value="Rytoastplanner@gmail.com" disabled required>
            </div>
            <div class="form-group"> <!--Email subject line-->
                <label for="subject">Subject:</label>
                <input type="text" id="subject" name="subject" class="form-control" value="**Confirm your Attendence** at the Ryerson Toastmasters Meeting on {{ meeting.starttime|date:'M d, Y' }}" required>
            </div>
            <div class="form-group"> <!--Email body/message-->
                <label for="body">Email Message:</label>
                <textarea type="text" id="body" name="body" class="form-control" rows="10" required>
Hi Toastmaster $/Name/$,

The Ryerson Toastmasters meeting on {{ meeting.starttime|date:'M d, Y' }} starting at {{meeting.starttime|time }} with the theme {{ meeting.theme }} is coming up!

You still haven't confirmed your attendance, make sure you do so ASAP! You are currently considered eligible to take on a role and may be scheduled soon.

You can CONFIRM your attendance using this link: rytoastplanner.herokuapp.com/confirm_attendance/{{ meeting.id }}/$/Name/$/T
You can DECLINE your attendance using this link: rytoastplanner.herokuapp.com/confirm_attendance/{{ meeting.id }}/$/Name/$/F

Stay Toasty,

Toastmaster {{ request.user.username }}
E: {{ request.user.email }}
                </textarea>
            </div>
            <button type="submit" class="btn btn-primary">Send Attendance Confirmation Email</button>


        </form>
    </div>

    <br>

    <!--Request for Roles Sign Up Emails Dashboard-->
    <div class="container container-sm col-title col-8">
        <h4>2) Roles Sign Up Request</h4>
        <p>Send an email to all members who have not signed up for a role yet at the meeting.</p>
        <p>List of members without a role: 
            {% for member in no_role_attendees %}
                <b>{{ member.username }}</b>, 
            {% endfor %}
        </p>

        <!--The actual email form-->
        <form action="/confirmation_emails/{{ meeting.id }}" method="POST">
            {% csrf_token %}
            <div class="form-group"> <!--Recipients list-->
                <label for="recipients">Recipients:</label>
                <input type="text" id="recipients" name="recipients" class="form-control" value="{% for member in no_role_attendees %}{{ member.email }} {% endfor %}" required>
            </div>
            <div class="form-group"> <!--Email that will send out the email-->
                <label for="from">From:</label>
                <input type="text" id="from" name="from" class="form-control" value="Rytoastplanner@gmail.com" disabled required>
            </div>
            <div class="form-group"> <!--Email subject line-->
                <label for="subject">Subject:</label>
                <input type="text" id="subject" name="subject" class="form-control" value="**Sign Up for a Role** at the Ryerson Toastmasters Meeting on {{ meeting.starttime|date:'M d, Y' }}" required>
            </div>
            <div class="form-group"> <!--Email body/message-->
                <label for="body">Email Message:</label>
                <textarea type="text" id="body" name="body" class="form-control" rows="10" required>
Hi Toastmaster $/Name/$,

The Ryerson Toastmasters meeting on {{ meeting.starttime|date:'M d, Y' }} starting at {{meeting.starttime|time }} with the theme {{ meeting.theme }} is coming up soon!

You are not currently signed up for a role during the meeting, but there are still some roles that need to be filled out.
If you would like to volunteer for a role you can use the following link: rytoastplanner.herokuapp.com/meeting/{{ meeting.id }}

The following roles still have to be filled for the meeting:{% for role in unfilled_roles %}
- {{ role}}{% endfor %}

Stay Toasty,

Toastmaster {{ request.user.username }}
E: {{ request.user.email }}
                </textarea>
            </div>
            <button type="submit" class="btn btn-primary">Send Role Sign Up Request Email</button>


        </form>
    </div>

    <br>

    <!--Final Meeting Reminder Emails Dashboard-->
    <div class="container container-sm col-title col-8">
        <h4>3) Final Meeting Reminder</h4>
        <p>Send an email to all members who have confirmed their attendance at the Meeting.</p>
        <p>List of members attending: 
            {% for member in confirmed_attendees %}
                <b>{{ member.username }}</b>, 
            {% endfor %}
        </p>

        <!--The actual email form-->
        <form action="/confirmation_emails/{{ meeting.id }}" method="POST">
            {% csrf_token %}
            <div class="form-group"> <!--Recipients list-->
                <label for="recipients">Recipients:</label>
                <input type="text" id="recipients" name="recipients" class="form-control" value="{% for member in confirmed_attendees %}{{ member.email }} {% endfor %}" required>
            </div>
            <div class="form-group"> <!--Email that will send out the email-->
                <label for="from">From:</label>
                <input type="text" id="from" name="from" class="form-control" value="Rytoastplanner@gmail.com" disabled required>
            </div>
            <div class="form-group"> <!--Email subject line-->
                <label for="subject">Subject:</label>
                <input type="text" id="subject" name="subject" class="form-control" value="**Final Meeting Reminder** for the Ryerson Toastmasters Meeting on {{ meeting.starttime|date:'M d, Y' }}" required>
            </div>
            <div class="form-group"> <!--Email body/message-->
                <label for="body">Email Message:</label>
                <textarea type="text" id="body" name="body" class="form-control" rows="10" required>
Hi Toastmaster $/Name/$,

The Ryerson Toastmasters meeting on {{ meeting.starttime|date:'M d, Y' }} starting at {{meeting.starttime|time }} with the theme {{ meeting.theme }} is coming up soon!

Thank you for telling me that you will be coming to this meeting.

The full agenda is now out on the website if you would like to print it.
View or print the agenda: rytoastplanner.herokuapp.com/meeting/{{ meeting.id }}

If you have a role, make sure you arrive early (5:50-6:00pm) so that the meeting can start on time.

See you there.

Stay Toasty,

Toastmaster {{ request.user.username }}
E: {{ request.user.email }}
                </textarea>
            </div>
            <button type="submit" class="btn btn-primary">Send Meeting Reminder Email</button>


        </form>
    </div>

{% endblock %}

agenda/templates/agenda/create_user.html
{% extends "agenda/layout.html" %}

{% block body %}
<div class="container-sm">

    <br>

    <h2>Create a New User</h2>

    <p>This will create a new user with the submitted username and a random password. For the member to use this account they will have to go through the password reset process.</p>

    <p>Please do not enter any spaces in the name, it messes with the emails sent out to members to confirm their attendance.</p>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'agenda:create_user' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username" required>
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <input class="btn btn-primary" type="submit" value="Create User">
    </form>

</div>
{% endblock %}

agenda/templates/agenda/delete_meeting_confirmation.html
{% extends "agenda/layout.html" %}

{% block body %}

<br><br>

<div class="container container-sm col-title">

    <h2>Confirm Permanent Meeting Deletion</h2>

    <p>Are you sure you want to delete the meeting on <b>{{ meeting.starttime }}</b> with the <b>{{ meeting.theme}}</b> theme?</p>
    <p>The meeting will be permanently deleted and the information will not be recoverable.</p>

    <form method="POST" action="{% url 'agenda:index' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">No, I want to keep the meeting</button>
    </form>

    <br>

    <form method="POST" action="{% url 'agenda:delete_meeting' meeting.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">YES, DELETE THE MEETING</button>
    </form>

</div>
{% endblock %}

agenda/templates/agenda/edit_attendance.html
{% extends 'agenda/layout.html' %}
{% load static %}

{% block title %}
    Edit Meeting {{ id }} Attendance
{% endblock %}

{% block body %}



{% endblock %}

agenda/templates/agenda/login.html
{% extends "agenda/layout.html" %}

{% block body %}
<div class="container-sm">

    <br>

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'agenda:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <p>Don't have an account? <a href="{% url 'agenda:register' %}">Register here.</a></p>

</div>
{% endblock %}

agenda/templates/agenda/profile.html
{% extends 'agenda/layout.html' %}
{% load static %}

{% block title %}
    index
{% endblock %}

{% block body %}
    


{% endblock%}

agenda/templates/agenda/register.html
{% extends "agenda/layout.html" %}

{% block body %}
<div class="container-sm">

    <br>

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'agenda:register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username" required>
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address" required>
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password" required>
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" required>
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <p>Already have an account? <a href="{% url 'login' %}">Log In here.</a></p>

</div>
{% endblock %}